/**
 * Service Worker — Generate XLSX files in a Service Worker context.
 *
 * This example intercepts fetch requests and generates XLSX files
 * entirely inside the Service Worker, without touching the main thread.
 *
 * Register from your page:
 *   navigator.serviceWorker.register('/sw.js', { type: 'module' });
 */

import init, { write } from 'https://cdn.jsdelivr.net/npm/modern-xlsx@0.5.0/wasm/modern_xlsx_wasm.js';

let initialized = false;

async function ensureInit() {
  if (initialized) return;
  // Service Workers support fetch-based WASM init
  await init(new URL('https://cdn.jsdelivr.net/npm/modern-xlsx@0.5.0/dist/modern-xlsx.wasm'));
  initialized = true;
}

self.addEventListener('install', (event) => {
  // Pre-initialize WASM during install
  event.waitUntil(ensureInit());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Intercept requests to /api/xlsx/generate
  if (url.pathname === '/api/xlsx/generate') {
    event.respondWith(handleGenerate());
    return;
  }
});

async function handleGenerate() {
  await ensureInit();

  const workbookJson = JSON.stringify({
    sheets: [
      {
        name: 'SW Generated',
        worksheet: {
          rows: [
            {
              index: 1,
              cells: [
                { ref: 'A1', cellType: 'sharedString', value: 'Generated by Service Worker' },
                { ref: 'B1', cellType: 'sharedString', value: new Date().toISOString() },
              ],
            },
          ],
          mergeCells: [],
          conditionalFormatting: [],
          dataValidations: [],
          hyperlinks: [],
          columns: [],
        },
      },
    ],
    styles: {
      fonts: [{}],
      fills: [{ patternType: 'none' }, { patternType: 'gray125' }],
      borders: [{}],
      cellXfs: [{}],
      numFmts: [],
      cellStyles: [],
      dxfs: [],
    },
  });

  const xlsxBytes = write(workbookJson);

  return new Response(xlsxBytes, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': 'attachment; filename="sw-generated.xlsx"',
    },
  });
}
