/**
 * Export Sales Report — modern-xlsx example
 *
 * Creates a professional multi-section sales report with:
 *   - Title row (merged, large font)
 *   - Data table with zebra striping
 *   - Summary row with SUM formulas
 *   - Number formatting (currency, percentages)
 *   - Conditional cell styles (red for negative growth)
 *   - Auto-filter on header row
 *   - Frozen header row
 *   - Column auto-width
 */

import { writeFileSync } from 'node:fs';
import { Workbook, StyleBuilder, drawTable, initWasm } from 'modern-xlsx';

// ---------------------------------------------------------------------------
// 1. Initialize the WASM engine (required once before any operation)
// ---------------------------------------------------------------------------
await initWasm();

// ---------------------------------------------------------------------------
// 2. Create workbook and sheet
// ---------------------------------------------------------------------------
const wb = new Workbook();
const ws = wb.addSheet('Sales Report');

// ---------------------------------------------------------------------------
// 3. Title row — merged across all columns, large font
// ---------------------------------------------------------------------------
const titleStyle = new StyleBuilder()
  .font({ bold: true, size: 20, color: '1F3864' })
  .alignment({ horizontal: 'center', vertical: 'center' })
  .build(wb.styles);

ws.cell('A1').value = 'Annual Sales Report 2025';
ws.cell('A1').styleIndex = titleStyle;
ws.addMergeCell('A1:G1');

// Subtitle
const subtitleStyle = new StyleBuilder()
  .font({ italic: true, size: 11, color: '666666' })
  .alignment({ horizontal: 'center' })
  .build(wb.styles);

ws.cell('A2').value = 'Generated by modern-xlsx';
ws.cell('A2').styleIndex = subtitleStyle;
ws.addMergeCell('A2:G2');

// ---------------------------------------------------------------------------
// 4. Sales data
// ---------------------------------------------------------------------------
const salesData = [
  { region: 'North America', q1: 125000, q2: 158000, q3: 142000, q4: 189000 },
  { region: 'Europe',        q1:  87000, q2: 112000, q3:  98000, q4: 134000 },
  { region: 'Asia Pacific',  q1: 213000, q2: 245000, q3: 221000, q4: 287000 },
  { region: 'Latin America', q1:  54000, q2:  61000, q3:  59000, q4:  72000 },
  { region: 'Middle East',   q1:  38000, q2:  42000, q3:  45000, q4:  51000 },
  { region: 'Africa',        q1:  21000, q2:  28000, q3:  25000, q4:  33000 },
];

// Compute derived columns
const rows = salesData.map((d) => {
  const total = d.q1 + d.q2 + d.q3 + d.q4;
  const growth = (d.q4 - d.q1) / d.q1; // Q4-over-Q1 growth
  return [d.region, d.q1, d.q2, d.q3, d.q4, total, growth];
});

// ---------------------------------------------------------------------------
// 5. Draw the data table using the table layout engine
// ---------------------------------------------------------------------------
const headers = ['Region', 'Q1', 'Q2', 'Q3', 'Q4', 'Total', 'Growth'];

const result = drawTable(wb, ws, {
  headers,
  rows,
  origin: 'A3', // Start below the title rows

  // Column configuration
  columns: [
    { header: 'Region',  width: 20, align: 'left' },
    { header: 'Q1',      width: 14, align: 'right', numberFormat: '$#,##0' },
    { header: 'Q2',      width: 14, align: 'right', numberFormat: '$#,##0' },
    { header: 'Q3',      width: 14, align: 'right', numberFormat: '$#,##0' },
    { header: 'Q4',      width: 14, align: 'right', numberFormat: '$#,##0' },
    { header: 'Total',   width: 16, align: 'right', numberFormat: '$#,##0' },
    { header: 'Growth',  width: 12, align: 'center', numberFormat: '0.0%' },
  ],

  // Styling
  headerColor: '2F5496',
  headerFont: { bold: true, size: 11, color: 'FFFFFF' },
  alternateRowColor: 'D6E4F0',
  borderStyle: 'thin',
  borderColor: 'B4C6E7',

  // Features
  freezeHeader: true,
  autoFilter: true,
});

// ---------------------------------------------------------------------------
// 6. Summary row with formulas (below the table)
// ---------------------------------------------------------------------------
const summaryRow = result.lastDataRow + 2; // 1-based worksheet row, +1 for header offset
const summaryStyle = new StyleBuilder()
  .font({ bold: true, size: 11 })
  .fill({ pattern: 'solid', fgColor: '1F3864' })
  .font({ bold: true, color: 'FFFFFF' })
  .numberFormat('$#,##0')
  .border({ top: { style: 'double', color: '1F3864' } })
  .build(wb.styles);

const summaryLabelStyle = new StyleBuilder()
  .font({ bold: true, size: 11, color: 'FFFFFF' })
  .fill({ pattern: 'solid', fgColor: '1F3864' })
  .border({ top: { style: 'double', color: '1F3864' } })
  .build(wb.styles);

ws.cell('A' + summaryRow).value = 'TOTAL';
ws.cell('A' + summaryRow).styleIndex = summaryLabelStyle;

// SUM formulas for each quarterly column (B through F)
const dataStart = result.firstDataRow + 1; // 1-based row
const dataEnd = result.lastDataRow + 1;

for (let c = 1; c <= 5; c++) {
  const col = String.fromCharCode(65 + c); // B, C, D, E, F
  const cell = ws.cell(col + summaryRow);
  cell.formula = `SUM(${col}${dataStart}:${col}${dataEnd})`;
  cell.styleIndex = summaryStyle;
}

// Average growth
const avgGrowthStyle = new StyleBuilder()
  .font({ bold: true, color: 'FFFFFF' })
  .fill({ pattern: 'solid', fgColor: '1F3864' })
  .numberFormat('0.0%')
  .border({ top: { style: 'double', color: '1F3864' } })
  .alignment({ horizontal: 'center' })
  .build(wb.styles);

const growthCell = ws.cell('G' + summaryRow);
growthCell.formula = `AVERAGE(G${dataStart}:G${dataEnd})`;
growthCell.styleIndex = avgGrowthStyle;

// ---------------------------------------------------------------------------
// 7. Conditional styling — highlight negative growth in red
// ---------------------------------------------------------------------------
const redPctStyle = new StyleBuilder()
  .font({ bold: true, color: 'CC0000' })
  .fill({ pattern: 'solid', fgColor: 'FFC7CE' })
  .numberFormat('0.0%')
  .alignment({ horizontal: 'center' })
  .border({
    left:   { style: 'thin', color: 'B4C6E7' },
    right:  { style: 'thin', color: 'B4C6E7' },
    top:    { style: 'thin', color: 'B4C6E7' },
    bottom: { style: 'thin', color: 'B4C6E7' },
  })
  .build(wb.styles);

// Apply red style to any negative-growth cell
rows.forEach((row, i) => {
  const growth = row[6];
  if (growth < 0) {
    const rowNum = dataStart + i;
    ws.cell('G' + rowNum).styleIndex = redPctStyle;
  }
});

// ---------------------------------------------------------------------------
// 8. Document properties
// ---------------------------------------------------------------------------
wb.docProperties = {
  title: 'Annual Sales Report 2025',
  creator: 'modern-xlsx example',
};

// ---------------------------------------------------------------------------
// 9. Write to file
// ---------------------------------------------------------------------------
const buffer = await wb.toBuffer();
writeFileSync('sales-report.xlsx', buffer);

console.log('Created sales-report.xlsx');
console.log(`  Sheets: ${wb.sheetCount}`);
console.log(`  Table range: ${result.range}`);
console.log(`  Data rows: ${rows.length}`);
console.log(`  Features: merged title, zebra striping, formulas, frozen header, auto-filter`);
